### ISSUE TITLE
Dobby: Fix updating version from current branch

### ISSUE THREAD

**Issue by addersuk** [simplybusiness/dobby#75]
## What

Upgrade the version from default branch.

## Why

So we can have the correct upgraded version if the branch is not updated with base.

## How

I think if we change this line to use the base branch https://github.com/simplybusiness/dobby/blob/8a72a059ea2c8f6ab5093735bcf1616fe4e9a697/lib/action.rb#L28-L32. It should be fixed.
To test this Try and update the version with dobby command twice.

## ACs

- [x] Version should be upgraded from default branch.
- [x] Should not upgrade the version if command run multiple times with same version

**Comment by moltenice** [comment]
Fixed on: https://github.com/simplybusiness/dobby/releases/tag/v3.1.0
