### ISSUE TITLE
Create Dobby V3 tag

### ISSUE THREAD

**Issue by addersuk** [simplybusiness/dobby#81]
## What

We want to maintain a v3 release for Dobby

## Why

To make it easier for everyone to use our GitHub Action as they will not have to update it regularly.

## How

Create a v3 tag on the repo that points to the last release

## ACs

- [x] We have a v3 tag that points to the most recent  release
- [x] We have updated all our repos to use the new v3 version
- [x] If you get a chance, please update other repos as well
- [x] Use reusable workflow for dobby

**Comment by punitcse** [comment]
This is the script you need to run. Unfortunately you cant upload a shell file.
You also have to install `comby` before running it.
```shell
#!/usr/bin/env bash

VERSION_FILE_PATH=$(find . -name "version.rb")

comby 'pr_commented: :[rest_of_code]' "pr_commented:
    uses: simplybusiness/github-action-reusable-workflows/.github/workflows/dobby.yaml@v1
    with:
      version_file_path: ${VERSION_FILE_PATH}
    secrets: inherit" .github/workflows/dobby*.yml  -match-newline-at-toplevel -in-place

```
